services:
  n8n:
    image: n8nio/n8n:${N8N_VERSION:-latest}
    container_name: n8n-infra
    restart: unless-stopped
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=n8n.127.0.0.1.traefik.me
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://n8n.127.0.0.1.traefik.me:9000/
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres-infra
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${N8N_DB:-n8n}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-admin}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-admin123}
    volumes:
      - ../../../volumes/n8n:/home/node/.n8n
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.127.0.0.1.traefik.me`)"
      - "traefik.http.routers.n8n.entrypoints=web"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
    networks:
      - infra-network

volumes:
  n8n-data:

networks:
  infra-network:
    external: true
