services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.12.0}
    container_name: elasticsearch-infra
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ../../../volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "${EXPOSE_ELASTIC_PORT:-127.0.0.1:9200}:9200"
    networks:
      - infra-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-8.12.0}
    container_name: kibana-infra
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`kibana.127.0.0.1.traefik.me`)"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"
    networks:
      - infra-network
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  elasticsearch-data:

networks:
  infra-network:
    external: true
