services:
  homepage:
    image: ghcr.io/gethomepage/homepage:${HOMEPAGE_VERSION:-latest}
    container_name: homepage-infra
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=homepage.127.0.0.1.traefik.me:9000,localhost:3000
    volumes:
      - ../../volumes/homepage:/app/config
    networks:
      - infra-network

networks:
  infra-network:
    external: true
