services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-16}
    container_name: postgres-infra
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - ../../../volumes/postgres:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "${EXPOSE_POSTGRES_PORT:-127.0.0.1:5432}:5432"
    networks:
      - infra-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-infra
    restart: unless-stopped
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ../../../volumes/pgadmin:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json:ro
      - ./pgpass:/pgpass:ro
    entrypoint: >
      /bin/sh -c "
      chmod 600 /pgpass;
      /entrypoint.sh
      "
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.127.0.0.1.traefik.me`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    networks:
      - infra-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
  pgadmin-data:

networks:
  infra-network:
    external: true
