services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_VERSION:-latest}
    container_name: gitlab-infra
    restart: unless-stopped
    hostname: gitlab.127.0.0.1.traefik.me
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.127.0.0.1.traefik.me:9000'
        gitlab_rails['initial_root_password'] = '${ADMIN_PASSWORD:-admin123}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        postgresql['enable'] = true
        redis['enable'] = true
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.127.0.0.1.traefik.me`)"
      - "traefik.http.routers.gitlab.entrypoints=web"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    networks:
      - infra-network
    shm_size: '256m'

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

networks:
  infra-network:
    external: true
