services:
  promtail:
    image: grafana/promtail:${PROMTAIL_VERSION:-latest}
    container_name: promtail-infra
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - infra-network

networks:
  infra-network:
    external: true
