services:
  odoo:
    image: odoo:${ODOO_VERSION:-17.0}
    container_name: odoo-infra
    restart: unless-stopped
    volumes:
      - odoo-data:/var/lib/odoo
      - odoo-addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo.rule=Host(`odoo.127.0.0.1.traefik.me`)"
      - "traefik.http.services.odoo.loadbalancer.server.port=8069"
    networks:
      - infra-network

volumes:
  odoo-data:
  odoo-addons:

networks:
  infra-network:
    external: true
