services:
  code-server:
    image: lscr.io/linuxserver/code-server:${CODE_SERVER_VERSION:-latest}
    container_name: code-server-infra
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/Madrid}
      - PASSWORD=${CODE_SERVER_PASSWORD:-admin123}
      - SUDO_PASSWORD=${CODE_SERVER_SUDO_PASSWORD:-admin123}
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - ../../../../volumes/code-server:/config
      - ../../../../:/config/workspace/infra:ro
    networks:
      - infra-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`code.127.0.0.1.traefik.me`)"
      - "traefik.http.routers.code-server.entrypoints=web"
      - "traefik.http.services.code-server.loadbalancer.server.port=8443"

networks:
  infra-network:
    external: true
