services:
  it-tools:
    image: corentinth/it-tools:${ITTOOLS_VERSION:-latest}
    container_name: it-tools-infra
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it-tools.rule=Host(`tools.127.0.0.1.traefik.me`) || Host(`it-tools.127.0.0.1.traefik.me`)"
      - "traefik.http.routers.it-tools.entrypoints=web"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
    networks:
      - infra-network

networks:
  infra-network:
    external: true
