services:
  traefik:
    image: traefik:${TRAEFIK_VERSION:-v3.0}
    container_name: traefik-infra
    restart: unless-stopped
    ports:
      - "9000:80"
      - "9443:443"
      - "8080:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ../../volumes/traefik:/letsencrypt
    networks:
      - infra-network

networks:
  infra-network:
    external: true
