services:
  traefik:
    image: traefik:${TRAEFIK_VERSION:-v3.0}
    container_name: traefik-infra
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=infra-network"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - "9000:80"
      - "9443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../volumes/traefik:/letsencrypt
    labels:
      - "traefik.enable=true"
      # Dashboard en puerto 80 (a traves de traefik mismo)
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.127.0.0.1.traefik.me`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=web"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
    networks:
      - infra-network

networks:
  infra-network:
    external: true
