services:
  adguard:
    image: adguard/adguardhome:${ADGUARD_VERSION:-latest}
    container_name: adguard-infra
    restart: unless-stopped
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.127.0.0.1.traefik.me`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000"
    networks:
      - infra-network

volumes:
  adguard-work:
  adguard-conf:

networks:
  infra-network:
    external: true
