services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: prometheus-infra
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../../../volumes/prometheus:/prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.127.0.0.1.traefik.me`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    networks:
      - infra-network

volumes:
  prometheus-data:

networks:
  infra-network:
    external: true
